// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID           int32
	FromWalletID int32
	ToWalletID   int32
	Amount       pgtype.Numeric
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Wallet struct {
	ID                  int32
	UserID              int32
	Address             string
	PublicKey           string
	EncryptedPrivateKey string
	Balance             pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
