name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Create env file
        run: |
          cat << EOF > .env
          ENV=${{ vars.ENV }}
          PORT=${{ vars.PORT }}
          GOOSE_DRIVER=${{ vars.GOOSE_DRIVER }}
          GOOSE_DBSTRING=${{ secrets.GOOSE_DBSTRING }}
          CONN_STR=${{ secrets.CONN_STR }}
          MAX_CONNECTIONS=${{ vars.MAX_CONNECTIONS }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_TOKEN_DURATION=${{ vars.JWT_TOKEN_DURATION }}
          ETHEREUM_URL=${{ vars.ETHEREUM_URL }}
          ETHEREUM_SECRET_KEY=${{ secrets.ETHEREUM_SECRET_KEY }}
          REDIS_ADDR=${{ vars.REDIS_ADDR }}
          REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_DB=${{ vars.REDIS_DB }}
          KAFKA_BROKERS=${{ vars.KAFKA_BROKERS }}
          KAFKA_TOPIC=${{ vars.KAFKA_TOPIC }}
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_PORT=${{ vars.SMTP_PORT }}
          SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          EOF

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Login to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

            # Pull the latest image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:${{ env.VERSION }}

            # Stop and remove existing container
            docker stop api-container || true
            docker rm api-container || true

            # Run new container with environment variables from file
            docker run -d \
              --name api-container \
              --restart unless-stopped \
              --network app-network \
              -p ${{ vars.PORT }}:${{ vars.PORT }} \
              --env-file .env \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:${{ env.VERSION }}

            # Clean up old images
            docker image prune -f

            # Verify container is running
            docker ps | grep api-container
